name: Sequential execution
on: push
jobs:
    lint_test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            
            - name: install node
              uses: actions/setup-node@v3
              with:
               node-version: 18

            - name: install dependencies
              run: npm ci

            - name: lint code
              run: npm run lint

            - name: test code
              run: npm run test


    build_deploy:
        needs: lint_test
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v3
          
          - name: install node
            uses: actions/setup-node@v3
            with:
             node-version: 18

          - name: install dependencies
            run: npm ci

          - name: Build Project
            run: npm run build

          - name: deploying application
            run: echo "Deploying ..."